import React, { useState } from 'react';

export function RiskPanel({ risks = [], onUpdateRiskStatus, isUpdating = false }) {
  const [severityFilter, setSeverityFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');

  const filteredRisks = risks.filter((r) => {
    const matchesSev = severityFilter === 'all' || r.severity === severityFilter;
    const matchesStatus = statusFilter === 'all' || r.status === statusFilter;
    return matchesSev && matchesStatus;
  });

  const getSeverityBadge = (s) => {
    switch (s) {
      case 'critical':
      case 'high': return 'rose';
      case 'medium': return 'amber';
      default: return 'neutral';
    }
  };

  const getStatusBadge = (st) => {
    switch (st) {
      case 'open': return 'rose';
      case 'monitoring': return 'amber';
      case 'mitigating': return 'cyan';
      case 'mitigated':
      case 'closed': return 'green';
      default: return 'neutral';
    }
  };

  return (
    <div className="cc-card">
      <div className="cc-card-header" style={{ flexWrap: 'wrap', gap: '8px' }}>
        <div className="cc-card-title">
          <span>⚠️</span>
          <span>Risk Register ({filteredRisks.length} / {risks.length})</span>
        </div>
        <div style={{ display: 'flex', gap: '6px' }}>
          <select
            className="cc-select"
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            style={{ width: '120px', padding: '4px 6px', fontSize: '11px' }}
          >
            <option value="all">All Severities</option>
            <option value="critical">Critical</option>
            <option value="high">High</option>
            <option value="medium">Medium</option>
            <option value="low">Low</option>
          </select>
          <select
            className="cc-select"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            style={{ width: '120px', padding: '4px 6px', fontSize: '11px' }}
          >
            <option value="all">All Statuses</option>
            <option value="open">Open</option>
            <option value="monitoring">Monitoring</option>
            <option value="mitigating">Mitigating</option>
            <option value="mitigated">Mitigated</option>
            <option value="closed">Closed</option>
          </select>
        </div>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        {filteredRisks.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '24px', color: 'var(--text-muted)', fontSize: '12px' }}>
            No recorded operational risks match filters.
          </div>
        ) : (
          filteredRisks.map((risk) => (
            <div
              key={risk.id}
              style={{
                backgroundColor: 'rgba(9, 13, 22, 0.65)',
                border: '1px solid var(--border-dim)',
                borderRadius: '6px',
                padding: '12px 14px',
                display: 'flex',
                flexDirection: 'column',
                gap: '6px',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '10px' }}>
                <div>
                  <div style={{ fontWeight: 600, fontSize: '12px', color: 'var(--text-main)' }}>
                    {risk.title}
                  </div>
                  <div style={{ fontSize: '11px', color: 'var(--text-dim)', marginTop: '2px' }}>
                    {risk.description}
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '4px', flexShrink: 0 }}>
                  <span className={`cc-badge ${getSeverityBadge(risk.severity)}`}>
                    {risk.severity?.toUpperCase()} SEV
                  </span>
                  <span className={`cc-badge ${getStatusBadge(risk.status)}`}>
                    {risk.status?.toUpperCase()}
                  </span>
                </div>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px', paddingTop: '6px', borderTop: '1px solid var(--border-dim)', fontSize: '10px', color: 'var(--text-muted)' }}>
                <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                  {risk.session_id && <span>Session: <strong>{risk.session_id}</strong></span>}
                  {risk.venue_id && <span>Venue: <strong>{risk.venue_id}</strong></span>}
                  {risk.source_change_id && (
                    <span className="cc-badge neutral" style={{ fontSize: '9px' }}>
                      Generated by {risk.source_change_id}
                    </span>
                  )}
                </div>

                {onUpdateRiskStatus && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                    {risk.status !== 'monitoring' && (
                      <button
                        className="cc-btn cc-btn-secondary cc-btn-sm"
                        disabled={isUpdating}
                        onClick={() => onUpdateRiskStatus(risk.id, 'monitoring')}
                        style={{ padding: '2px 5px', fontSize: '9px' }}
                      >
                        Monitoring
                      </button>
                    )}
                    {risk.status !== 'mitigating' && (
                      <button
                        className="cc-btn cc-btn-secondary cc-btn-sm"
                        disabled={isUpdating}
                        onClick={() => onUpdateRiskStatus(risk.id, 'mitigating')}
                        style={{ padding: '2px 5px', fontSize: '9px' }}
                      >
                        Mitigating
                      </button>
                    )}
                    {risk.status !== 'mitigated' && (
                      <button
                        className="cc-btn cc-btn-primary cc-btn-sm"
                        disabled={isUpdating}
                        onClick={() => onUpdateRiskStatus(risk.id, 'mitigated')}
                        style={{ padding: '2px 5px', fontSize: '9px', backgroundColor: 'var(--accent-emerald)' }}
                      >
                        Mitigated
                      </button>
                    )}
                  </div>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

export default RiskPanel;
